[package]
name = "cat-printd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
btleplug = { version = "0.11.8", features = ["serde"] }
uuid = "1.19.0"
image = "0.25.9"
imageproc = "0.25.0"
ab_glyph = "0.2.32"
