[package]
name = "cat-printd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
btleplug = { version = "0.11.8", features = ["serde"] }
serde = { version = "1.0.228", features=["derive"] }
uuid = "1.19.0"
